### ISSUE TITLE
Output: Fix printout for initialize

### ISSUE THREAD

**Issue by stephenlago** [taylorchasewhite/vocatus#15]
Errant text is appearing when first booting up the arduino

**Comment by taylorchasewhite** [comment]
This might be the issue? I'll look at adding a delay. Definitely seems like a hardware issue based on the behavior I'm seeing.
https://stackoverflow.com/questions/11282119/strange-initial-output-using-serial-print

**Comment by stephenlago** [comment]
This hasn't been happening for a while. Closing as could not reproduce.
