### ISSUE TITLE
SB: Make Pretty 

### ISSUE THREAD

**Issue by stephenlago** [taylorchasewhite/vocatus#18]
Make a nice UI for the status board given the new variables being sent

**Comment by taylorchasewhite** [comment]
![screen shot 2018-05-15 at 1 25 54 am](https://user-images.githubusercontent.com/3686217/40040227-f9a6747a-57de-11e8-91b7-86d0a46d1e6e.png)

**Comment by taylorchasewhite** [comment]
![screen shot 2018-05-15 at 1 26 39 am](https://user-images.githubusercontent.com/3686217/40040266-2f818b20-57df-11e8-878d-dc678d9ccd76.png)
![screen shot 2018-05-15 at 1 27 17 am](https://user-images.githubusercontent.com/3686217/40040267-2f926940-57df-11e8-810f-7ab0540399b6.png)
![screen shot 2018-05-15 at 1 26 56 am](https://user-images.githubusercontent.com/3686217/40040269-2fa999d0-57df-11e8-8e93-9fb49d2ea0b5.png)

**Comment by taylorchasewhite** [comment]
Now the background randomly generates when you run the status board. The font is using pencilPete font (install the ttf on your machine, it's included in our repository. 

I think this issue documentation should be more specific in order for us to actually determine when the status board is pretty or not.

**Comment by taylorchasewhite** [comment]
This is where I landed:
![screen shot 2018-05-15 at 2 03 14 am](https://user-images.githubusercontent.com/3686217/40041676-743ce516-57e4-11e8-8632-7cf8e96d3cf8.png)
![screen shot 2018-05-15 at 2 04 05 am](https://user-images.githubusercontent.com/3686217/40041678-744e8168-57e4-11e8-9d39-0b9c5e2e3833.png)

**Comment by taylorchasewhite** [comment]
@stephenlago please review and close.

**Comment by taylorchasewhite** [comment]
Addressed TODO comments, marking as closed--let me know if we should have a system to have the alternate person close issues
