### ISSUE TITLE
Implement ability to keep track of a single beer

### ISSUE THREAD

**Issue by stephenlago** [taylorchasewhite/vocatus#55]
Implement the ability to accurately keep track of when a drink is in progress and when a drink has ended, according to the definition.

**Comment by taylorchasewhite** [comment]
What should cause the beer count to go up?

Gut feel: >=10 mL, <=26 mL (2 beers) , 2 seconds elapsed between flow.

**Comment by stephenlago** [comment]
Closing as duplicate of [issue #32](https://github.com/taylorchasewhite/vocatus/issues/32)
