### ISSUE TITLE
Hitting Reset Button Repeatedly causes problems

### ISSUE THREAD

**Issue by taylorchasewhite** [taylorchasewhite/vocatus#84]
**Describe the bug**
Hitting the reset button too many times causes the arduino to hit some kind of overflow. After subsequent presses, it no longer works.

**Expected behavior**
Don't break

**Comment by stephenlago** [comment]
Problem was being caused by creating new Record objects every time the reset button was pressed. Not clear on why that caused the issue. 
Fixed by adding a reset function to each sub-class instead of just switching to a new object.
