### ISSUE TITLE
Overflow issue when too many drinks poured

### ISSUE THREAD

**Issue by taylorchasewhite** [taylorchasewhite/vocatus#93]
**Describe the bug**
A problem occurs after a number of drinks have been poured into the arduino. What happens is that the volume, time and other numbers that are reported back through the Record->DisplayManager->interface are incorrect and erratic in their value (as evidenced by negative numbers which is impossible in volume and time measurements).

This is likely due to some memory problem. The error exists in both LCD and Debug modes but is more pronounced in Debug mode as all the data is output at the same time.

**To Reproduce**
1. Turn on the arduino in debug mode.
2. Start pouring a drink in (any volume will do--small is better as you'll be doing quite a few)
3. Eventually the data will become unstable and negative.

I believe that the DisplayManager stops outputting altogether but I could be wrong on that.

**Expected behavior**
Be able to pour beer indefinitely into the Arduino while it is powered on.

**Additional context**
We might be able to use the [MemoryFree](https://playground.arduino.cc/Code/AvailableMemory) library to monitor and debug where we are leaking RAM.

**Comment by stephenlago** [comment]
Caused by memory leak; fixed.
